<?php

/**
 * @file
 * Examples demonstrating the Drupal Form API.
 */

/**
 * @defgroup registration Example: Form API
 * @ingroup examples
 * @{
 * Examples demonstrating the Drupal Form API.
 *
 * The Form Example module is a part of the Examples for Developers Project
 * and provides various Drupal Form API Examples. You can download and
 * experiment with this code at the
 * @link http://drupal.org/project/examples Examples for Developers project page. @endlink
 */

/**
 * Implements hook_menu() to set up the URLs (menu entries) for the
 * form examples.
 */
function registration_menu() {
  $items = array();
  $items['macedonia/registration'] = array(
    'title' => 'Macedonia registration',
    'page callback' => 'registration_intro',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  $items['macedonia/registration/process'] = array(
    'title' => 'Form process',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('registration_process_1'),
    'access callback' => TRUE,
    'description' => 'A set of ten processs',
    'file' => 'registration_process.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['macedonia/registration/process/8'] = array(
    'title' => '#8',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('registration_process_8'),
    'access callback' => TRUE,
    'description' => 'process 8: Basic multistep form',
    'type' => MENU_LOCAL_TASK,
    'file' => 'registration_process.inc',
  );

  return $items;
}

function registration_intro() {
  $markup = t('The form example module provides a process, extensible multistep example, an element example, and a #states example');
  return array('#markup' => $markup);
}

/**
 * Implements hook_help() to provide a bit of help.
 */
function registration_help($path, $arg) {
  switch ($path) {
    case 'macedonia/registration/process':
      // TODO: Update the URL.
      $help = t('This form example process for Drupal 7 is the code from the <a href="http://drupal.org/node/262422">Handbook 10-step process</a>');
      break;
    case 'macedonia/registration/element_example':
      $help = t('The Element Example shows how modules can provide their own Form API element types. Four different element types are demonstrated.');
      break;
  }
  if (!empty($help)) {
    return '<p>' . $help . '</p>';
  }
}

/**
* Implements hook_element_info().
*
* To keep the various pieces of the example together, this just returns
* _registration_elements().
*/
function registration_element_info() {
  require_once('registration_elements.inc');
  return _registration_element_info();
}

/**
* Implements hook_theme().
*
* The only theme implementation is by the element example. To keep the various
* parts of the example together, this actually returns
* _registration_element_theme().
*/
function registration_theme($existing, $type, $theme, $path) {
  require_once('registration_elements.inc');
  return _registration_element_theme($existing, $type, $theme, $path);
}
/**
 * @} End of "defgroup registration".
 */
